---
abstract: 'IO::All of it to Graham and Damian!'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: IO-All
no_index:
  directory:
    - inc
    - t
requires:
  IO::String: 0
  perl: 5.6.1
version: 0.39
