--- #YAML:1.0
name:               IPC-Cmd
version:            0.56
abstract:           A cross platform way of running (interactive) commandline programs.
author:
    - Jos Boumans <kane[at]cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::MakeMaker:  0
    File::Spec:           0
    Locale::Maketext::Simple:  0
    Module::Load::Conditional:  0
    Params::Check:        0.20
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
